### get the resources
GET https://backend-part3-1jud.onrender.com/api/persons

### send new resource
POST https://backend-part3-1jud.onrender.com/api/persons
Content-Type: application/json

{
  "name": "El Rorri",
  "number": "56-12-569874"
}