### get the resources
GET http://localhost:3001/api/persons

### send new resource
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "personName": "El Rorri",
  "number": 64164878
}
### delete resource

DELETE http://localhost:3001/api/persons/6654dcf8a50fe1afea3215b9